### ISSUE TITLE
Comma in card name

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#17]
Pip, Epic Arbiter has a comma in its name. This is the second card with a comma. I believe there is something hardcoded for the other one.

We should get rid of this hard coded exclusion as obviously synapticon considers commata in card names normal.

**Comment by hunterhogan** [comment]
Your point is well taken, especially because there are three cards with commas

Kapak, the Deceiver

Kogoth, the Consumer

Pip, Epic Arbiter

When considering solutions, you might want to think of other special characters that could potentially appear in future cards and, if possible, implement a solution that anticipates these as-of-yet unused special characters.

We already have cards that use apostrophes, and I assume you have dealt with that problem. 

Jotun, Sacred Guardian is a raid and not a card, but it easily could have been named “Jotun: The Sacred Guardian” with a colon instead of a comma. Card names with a colon are hard to imagine but raids, missions, and side missions with colons and semicolons are plausible.

The various types of quotation marks, however, are the characters I would be most concerned about. Card names like Dwight "Ike" Eisenhower or Lou "The Lizard" Maloney are plausible, and maybe even likely if there are future cards that are tributes to players.

As practicing programmers, I am sure you know better than I know which special characters would give you the most trouble. To avoid a big headache in the future, you might benefit from spending a little time looking at the list of troublesome special characters and thinking about which characters might show up in various XML files for the game. 

Just my 2 cents.

**Comment by FKuerten** [comment]
Thanks for your input. Unfortunately xml can contain (inside quoted strings) almost any character.
We need to investigate why the comma is a special case in the simulator.
I suspect that the idea was to somewhere separate a list of cards.

**Comment by MrHen** [comment]
83847a6503f68ed81b500b91e58099b3d13e85eb

I added some tests for deck hashes using cards with commas in their name; they are currently passing.

**Comment by MrHen** [comment]
I am switching this to an Enhancement because, as far as I know, we have no evidence that a bug exists, here. We should still fix that horrid hack for the other card with comma in its name.

**Comment by FKuerten** [comment]
If I recall this correctly, this only happens when importing text files with actual card names using one of the many methods in class CardDB.
Stuff like saved decks, owned cards and such. However I agree that this is not urgent.

**Comment by MrHen** [comment]
I am closing this. When we have a real bug we can reopen it.
