### ISSUE TITLE
branches?

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#58]
What is the purpose of the staging branch?
What is the purpose of the test branch?

**Comment by MrHen** [comment]
Test branch was for creating test cases. That can probably go away now because I have been using the test repo to add new tests.

Staging branch was intended to be a pre-release branch to keep the release branch clean but it didn't work out that way. I'm also not sure Git cares about things like that; in retrospect we could probably just get rid of it.

**Comment by MrHen** [comment]
Okay, I deleted the staging branch. The tests branch was already deleted.

**Comment by FKuerten** [comment]
test repo?

**Comment by MrHen** [comment]
Archiving repo and closing all issues.
